"""Local domain models for structured TripPilot output."""

from datetime import date as Date
from typing import Any

from pydantic import AliasChoices, BaseModel, Field, field_validator, model_validator


class Location(BaseModel):
    """Geographic coordinates shared by attractions, hotels and meals."""

    longitude: float = Field(..., ge=-180, le=180, description="经度")
    latitude: float = Field(..., ge=-90, le=90, description="纬度")


class Attraction(BaseModel):
    """A candidate or scheduled point of interest."""

    poi_id: str | None = Field(default=None, description="高德 POI ID")
    name: str = Field(..., min_length=1, description="景点名称")
    address: str = Field(default="", description="景点地址")
    type_code: str | None = Field(default=None, description="高德 POI 类型编码")
    location: Location | None = Field(default=None, description="经纬度坐标")
    description: str = Field(default="", description="景点描述")
    category: str = Field(default="attraction", description="景点类别")
    rating: float | None = Field(default=None, ge=0, le=5, description="评分")
    visit_duration: int = Field(default=120, gt=0, description="建议游览时长（分钟）")
    ticket_price: float = Field(default=0, ge=0, description="门票价格（元）")
    image_url: str | None = Field(default=None, description="景点图片 URL")


class WeatherInfo(BaseModel):
    """Daily weather normalized from an external provider such as AMap."""

    date: Date = Field(..., description="天气日期")
    day_weather: str = Field(..., min_length=1, description="白天天气")
    night_weather: str | None = Field(default=None, description="夜间天气")
    day_temp: int | None = Field(default=None, description="白天气温（摄氏度）")
    night_temp: int | None = Field(default=None, description="夜间气温（摄氏度）")
    wind_direction: str | None = Field(default=None, description="风向")
    wind_power: str | None = Field(default=None, description="风力")

    @field_validator("day_temp", "night_temp", mode="before")
    @classmethod
    def parse_temperature(cls, value: Any) -> Any:
        """Normalize values such as ``16°C`` and ``16℃`` to integers."""
        if isinstance(value, str):
            normalized = (
                value.replace("°C", "")
                .replace("℃", "")
                .replace("°", "")
                .strip()
            )
            if not normalized or normalized in {"--", "-"}:
                return None
            return int(normalized)
        return value


class Hotel(BaseModel):
    """A hotel candidate returned by search or selected by the planner."""

    poi_id: str | None = Field(default=None, description="高德 POI ID")
    name: str = Field(..., min_length=1, description="酒店名称")
    address: str = Field(default="", description="酒店地址")
    type_code: str | None = Field(default=None, description="高德 POI 类型编码")
    location: Location | None = Field(default=None, description="酒店位置")
    rating: float | None = Field(default=None, ge=0, le=5, description="评分")
    price_range: str = Field(default="", description="展示用价格区间")
    distance: str = Field(default="", description="与核心景点的距离说明")
    hotel_type: str = Field(
        default="",
        description="酒店类型",
    )
    estimated_cost_per_night: float = Field(
        default=0,
        ge=0,
        description="每晚预估费用（元）",
    )


class Meal(BaseModel):
    """A meal suggestion generated by the planner."""

    poi_id: str | None = Field(default=None, description="高德 POI ID")
    type_code: str | None = Field(default=None, description="高德 POI 类型编码")
    meal_type: str = Field(
        ...,
        min_length=1,
        validation_alias=AliasChoices("meal_type", "type"),
        description="餐饮类型，例如 breakfast/lunch/dinner/snack",
    )
    name: str = Field(..., min_length=1, description="餐饮名称")
    address: str = Field(default="", description="地址")
    location: Location | None = Field(default=None, description="经纬度坐标")
    description: str = Field(default="", description="餐饮说明")
    rating: float | None = Field(default=None, ge=0, le=5, description="评分")
    estimated_cost: float = Field(default=0, ge=0, description="预估费用（元）")


class DayPlan(BaseModel):
    """One calendar day's structured itinerary."""

    date: Date = Field(..., description="行程日期")
    day_index: int = Field(..., ge=1, description="第几天（从 1 开始）")
    title: str = Field(default="", description="当日主题")
    description: str = Field(default="", description="当日行程说明")
    attractions: list[Attraction] = Field(default_factory=list, description="景点列表")
    meals: list[Meal] = Field(default_factory=list, description="餐饮安排")
    hotel: Hotel | None = Field(default=None, description="酒店信息")
    transportation: str = Field(default="", description="交通方式")
    accommodation: str = Field(default="", description="住宿安排说明")
    estimated_daily_cost: float = Field(default=0, ge=0, description="当日预估费用")


class Budget(BaseModel):
    """Deterministic budget summary calculated by Python."""

    attraction_cost: float = Field(default=0, ge=0, description="景点门票总费用")
    hotel_cost: float = Field(default=0, ge=0, description="酒店总费用")
    meal_cost: float = Field(default=0, ge=0, description="餐饮总费用")
    transportation_cost: float = Field(default=0, ge=0, description="交通总费用")
    total: float = Field(default=0, ge=0, description="预估总费用")


class TripPlan(BaseModel):
    """Top-level structured result returned by the TripPilot workflow."""

    city: str = Field(..., min_length=1, description="目的地城市")
    start_date: Date = Field(..., description="旅行开始日期")
    end_date: Date = Field(..., description="旅行结束日期")
    days: list[DayPlan] = Field(default_factory=list, description="每日行程")
    weather_info: list[WeatherInfo] = Field(default_factory=list, description="天气信息")
    overall_suggestions: str = Field(..., description="总体建议")
    budget: Budget | None = Field(default=None, description="预算信息")

    @model_validator(mode="after")
    def validate_dates(self) -> "TripPlan":
        if self.end_date < self.start_date:
            raise ValueError("end_date must be on or after start_date")
        return self
